"""empty message

Revision ID: 2716d29107d3
Revises: 6b4b87d97108
Create Date: 2021-07-21 23:05:16.388517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2716d29107d3'
down_revision = '6b4b87d97108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('is_delete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'is_delete')
    # ### end Alembic commands ###
