"""empty message

Revision ID: 6b4b87d97108
Revises: d503b6f90805
Create Date: 2021-07-20 22:57:39.009267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4b87d97108'
down_revision = 'd503b6f90805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('icon', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'icon')
    # ### end Alembic commands ###
